FROM node:22

WORKDIR /app

COPY package*.json .
COPY tsconfig.json .

RUN npm install

COPY src src

COPY dist dist

ADD public.tar.gz .

ARG PORT_ARG=3000
ENV PORT=$PORT_ARG

EXPOSE $PORT_ARG
CMD [ "npm", "start" ]