version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: some-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: --noauth

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app  # Ensure the app has access to your project files
    entrypoint: ["./wait-for-it.sh", "some-mongo:27017", "--", "npm", "start"]

volumes:
  mongo-data:
