version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: some-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data: